// 필카톡 사진 달력 서버
// Node.js 22+
// PostgreSQL + Cloudflare R2 + Render

const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const { Pool } = require('pg');

const {
  S3Client,
  PutObjectCommand,
  DeleteObjectCommand,
} = require('@aws-sdk/client-s3');


// ============================================================
// 기본 설정
// ============================================================

const PORT = Number(process.env.PORT || 3000);

const MAX_PER_USER = Number(process.env.MAX_PER_USER || 10);
const MAX_IMAGE_MB = Number(process.env.MAX_IMAGE_MB || 15);
const MAX_BYTES = MAX_IMAGE_MB * 1024 * 1024;

const SESSION_MS = 7 * 24 * 60 * 60 * 1000;

const LOGIN_MAX_ATTEMPTS = 5;
const LOGIN_WINDOW_MS = 15 * 60 * 1000;
const LOGIN_BLOCK_MS = 15 * 60 * 1000;

const PUBLIC_DIR = path.join(__dirname, 'public');


// ============================================================
// 환경변수 검사
// ============================================================

const DATABASE_URL = process.env.DATABASE_URL || '';
const SESSION_SECRET = process.env.SESSION_SECRET || '';
const ADMIN_KEY = process.env.ADMIN_KEY || '';

const R2_ENDPOINT = process.env.R2_ENDPOINT || '';
const R2_ACCESS_KEY_ID = process.env.R2_ACCESS_KEY_ID || '';
const R2_SECRET_ACCESS_KEY = process.env.R2_SECRET_ACCESS_KEY || '';
const R2_BUCKET = process.env.R2_BUCKET || '';
const R2_PUBLIC_URL = process.env.R2_PUBLIC_URL || '';

if (!DATABASE_URL) {
  throw new Error('DATABASE_URL 환경변수가 필요합니다.');
}

if (Buffer.byteLength(SESSION_SECRET) < 32) {
  throw new Error(
    'SESSION_SECRET 환경 변수에 32바이트 이상의 비밀값을 설정하세요.'
  );
}

if (!ADMIN_KEY) {
  throw new Error(
    'ADMIN_KEY 환경변수를 설정하세요.'
  );
}

const missingR2 = [];

if (!R2_ENDPOINT) missingR2.push('R2_ENDPOINT');
if (!R2_ACCESS_KEY_ID) missingR2.push('R2_ACCESS_KEY_ID');
if (!R2_SECRET_ACCESS_KEY) missingR2.push('R2_SECRET_ACCESS_KEY');
if (!R2_BUCKET) missingR2.push('R2_BUCKET');
if (!R2_PUBLIC_URL) missingR2.push('R2_PUBLIC_URL');

if (missingR2.length > 0) {
  throw new Error(
    `R2 환경변수가 없습니다: ${missingR2.join(', ')}`
  );
}


// ============================================================
// PostgreSQL 연결
// ============================================================

const db = new Pool({
  connectionString: DATABASE_URL,
  ssl: {
    rejectUnauthorized: false,
  },
});


// ============================================================
// Cloudflare R2 연결
// ============================================================

const r2 = new S3Client({
  region: 'auto',

  endpoint: R2_ENDPOINT,

  credentials: {
    accessKeyId: R2_ACCESS_KEY_ID,
    secretAccessKey: R2_SECRET_ACCESS_KEY,
  },
});


// ============================================================
// DB 초기화
// ============================================================

async function initializeDatabase() {
  await db.query(`
    CREATE TABLE IF NOT EXISTS users (
      id TEXT PRIMARY KEY,
      nickname TEXT NOT NULL,
      nick_key TEXT NOT NULL UNIQUE,
      pin_salt TEXT NOT NULL,
      pin_hash TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS photos (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      month TEXT NOT NULL,
      nickname TEXT NOT NULL,
      nick_key TEXT NOT NULL,
      caption TEXT DEFAULT '',
      filename TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      owner_id TEXT DEFAULT '',
      thumb TEXT DEFAULT ''
    )
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS votes (
      photo_id INTEGER NOT NULL
        REFERENCES photos(id)
        ON DELETE CASCADE,

      voter_id TEXT NOT NULL,

      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

      PRIMARY KEY (photo_id, voter_id)
    )
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS login_attempts (
      bucket TEXT PRIMARY KEY,

      count INTEGER NOT NULL DEFAULT 0,

      window_started BIGINT NOT NULL,

      blocked_until BIGINT NOT NULL DEFAULT 0
    )
  `);

  await db.query(`
    CREATE INDEX IF NOT EXISTS idx_photos_month
    ON photos(month)
  `);

  console.log('PostgreSQL 데이터베이스 초기화 완료');
}


// ============================================================
// MIME
// ============================================================

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',

  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.png': 'image/png',
  '.webp': 'image/webp',

  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
};


// ============================================================
// JSON 응답
// ============================================================

function send(res, code, obj) {
  if (res.headersSent) return;

  res.writeHead(code, {
    'Content-Type': 'application/json; charset=utf-8',
  });

  res.end(JSON.stringify(obj));
}


// ============================================================
// 관리자 인증
// ============================================================

function isAdmin(req) {
  const supplied = Buffer.from(
    String(req.headers['x-admin-key'] || '')
  );

  const expected = Buffer.from(ADMIN_KEY);

  return (
    supplied.length === expected.length &&
    crypto.timingSafeEqual(supplied, expected)
  );
}


// ============================================================
// Body 읽기
// ============================================================

function readBody(req, limit) {
  return new Promise((resolve, reject) => {
    let size = 0;

    const chunks = [];

    let rejected = false;

    req.on('data', (chunk) => {
      if (rejected) return;

      size += chunk.length;

      if (size > limit) {
        rejected = true;

        reject(new Error('too_large'));

        req.resume();

        return;
      }

      chunks.push(chunk);
    });

    req.on('end', () => {
      if (!rejected) {
        resolve(Buffer.concat(chunks));
      }
    });

    req.on('error', (error) => {
      if (!rejected) {
        reject(error);
      }
    });
  });
}


async function readJson(req) {
  const buffer = await readBody(
    req,
    64 * 1024
  );

  try {
    return JSON.parse(
      buffer.toString() || '{}'
    );
  } catch {
    throw new Error('bad_json');
  }
}


// ============================================================
// 입력값 처리
// ============================================================

function validMonth(month) {
  return /^\d{4}-(0[1-9]|1[0-2])$/.test(
    month || ''
  );
}


function cleanNick(value) {
  return String(value || '')
    .normalize('NFKC')
    .trim()
    .replace(/\s+/g, ' ')
    .slice(0, 20);
}


function nickKeyOf(nickname) {
  return cleanNick(nickname)
    .toLocaleLowerCase('ko-KR');
}


function hdr(req, name) {
  try {
    return decodeURIComponent(
      String(req.headers[name] || '')
    );
  } catch {
    return '';
  }
}


// ============================================================
// Cookie
// ============================================================

function getCookie(req, name) {
  const cookies = String(
    req.headers.cookie || ''
  ).split(';');

  for (const part of cookies) {
    const i = part.indexOf('=');

    if (i < 0) continue;

    const key = part
      .slice(0, i)
      .trim();

    if (key !== name) continue;

    try {
      return decodeURIComponent(
        part.slice(i + 1).trim()
      );
    } catch {
      return '';
    }
  }

  return '';
}


// ============================================================
// 세션
// ============================================================

function sign(payload) {
  return crypto
    .createHmac(
      'sha256',
      SESSION_SECRET
    )
    .update(payload)
    .digest();
}


function setSession(res, userId) {
  const payload = Buffer
    .from(
      JSON.stringify({
        sub: userId,
        exp: Date.now() + SESSION_MS,
      })
    )
    .toString('base64url');

  const signature = sign(payload)
    .toString('base64url');

  const secure =
    process.env.NODE_ENV === 'production'
      ? '; Secure'
      : '';

  res.setHeader(
    'Set-Cookie',

    `session=${payload}.${signature}; ` +
    `Path=/; ` +
    `HttpOnly; ` +
    `SameSite=Strict; ` +
    `Max-Age=${Math.floor(SESSION_MS / 1000)}` +
    secure
  );
}


function clearSession(res) {
  const secure =
    process.env.NODE_ENV === 'production'
      ? '; Secure'
      : '';

  res.setHeader(
    'Set-Cookie',

    `session=; ` +
    `Path=/; ` +
    `HttpOnly; ` +
    `SameSite=Strict; ` +
    `Max-Age=0` +
    secure
  );
}


async function authenticatedUser(req) {
  const token = getCookie(
    req,
    'session'
  );

  const separator =
    token.lastIndexOf('.');

  if (separator < 1) {
    return null;
  }

  const payload =
    token.slice(0, separator);

  let suppliedSignature;

  try {
    suppliedSignature =
      Buffer.from(
        token.slice(separator + 1),
        'base64url'
      );
  } catch {
    return null;
  }

  const expectedSignature =
    sign(payload);

  if (
    suppliedSignature.length !==
    expectedSignature.length
  ) {
    return null;
  }

  if (
    !crypto.timingSafeEqual(
      suppliedSignature,
      expectedSignature
    )
  ) {
    return null;
  }

  try {
    const data = JSON.parse(
      Buffer.from(
        payload,
        'base64url'
      ).toString()
    );

    if (
      !data.sub ||
      !Number.isFinite(data.exp) ||
      data.exp < Date.now()
    ) {
      return null;
    }

    const result = await db.query(
      `
      SELECT
        id,
        nickname,
        nick_key
      FROM users
      WHERE id = $1
      `,
      [data.sub]
    );

    return result.rows[0] || null;
  } catch {
    return null;
  }
}


async function requireUser(req, res) {
  const user =
    await authenticatedUser(req);

  if (!user) {
    send(res, 401, {
      error: '먼저 로그인해주세요.',
    });

    return null;
  }

  return user;
}


// ============================================================
// PIN
// ============================================================

function pinHash(pin, salt) {
  return crypto.scryptSync(
    pin,
    salt,
    64
  );
}


// ============================================================
// 로그인 제한
// ============================================================

function attemptBucket(req, nickKey) {
  const ip =
    req.socket.remoteAddress ||
    'unknown';

  return crypto
    .createHmac(
      'sha256',
      SESSION_SECRET
    )
    .update(`${nickKey}\n${ip}`)
    .digest('hex');
}


async function isLoginBlocked(bucket) {
  const result = await db.query(
    `
    SELECT blocked_until
    FROM login_attempts
    WHERE bucket = $1
    `,
    [bucket]
  );

  const row = result.rows[0];

  return Boolean(
    row &&
    Number(row.blocked_until) >
      Date.now()
  );
}


async function failLogin(bucket) {
  const now = Date.now();

  const result = await db.query(
    `
    SELECT
      count,
      window_started
    FROM login_attempts
    WHERE bucket = $1
    `,
    [bucket]
  );

  const row = result.rows[0];

  const inWindow =
    row &&
    now - Number(row.window_started) <
      LOGIN_WINDOW_MS;

  const count =
    inWindow
      ? Number(row.count) + 1
      : 1;

  const windowStarted =
    inWindow
      ? Number(row.window_started)
      : now;

  const blockedUntil =
    count >= LOGIN_MAX_ATTEMPTS
      ? now + LOGIN_BLOCK_MS
      : 0;

  await db.query(
    `
    INSERT INTO login_attempts
      (
        bucket,
        count,
        window_started,
        blocked_until
      )
    VALUES
      ($1, $2, $3, $4)

    ON CONFLICT(bucket)
    DO UPDATE SET
      count = EXCLUDED.count,
      window_started = EXCLUDED.window_started,
      blocked_until = EXCLUDED.blocked_until
    `,
    [
      bucket,
      count,
      windowStarted,
      blockedUntil,
    ]
  );
}


// ============================================================
// 이미지 파일 형식 검사
// ============================================================

function sniff(buffer) {
  // JPEG
  if (
    buffer.length > 3 &&
    buffer[0] === 0xff &&
    buffer[1] === 0xd8 &&
    buffer[2] === 0xff
  ) {
    return 'jpg';
  }

  // PNG
  if (
    buffer.length >= 8 &&
    buffer.subarray(0, 8).equals(
      Buffer.from([
        0x89,
        0x50,
        0x4e,
        0x47,
        0x0d,
        0x0a,
        0x1a,
        0x0a,
      ])
    )
  ) {
    return 'png';
  }

  // WEBP
  if (
    buffer.length >= 12 &&
    buffer.subarray(0, 4).toString() ===
      'RIFF' &&
    buffer.subarray(8, 12).toString() ===
      'WEBP'
  ) {
    return 'webp';
  }

  return null;
}


function contentTypeFor(extension) {
  switch (extension) {
    case 'jpg':
      return 'image/jpeg';

    case 'png':
      return 'image/png';

    case 'webp':
      return 'image/webp';

    default:
      return 'application/octet-stream';
  }
}


// ============================================================
// R2 URL
// ============================================================

function urlOf(filename) {
  return (
    R2_PUBLIC_URL.replace(/\/$/, '') +
    '/' +
    encodeURIComponent(filename)
  );
}


// ============================================================
// R2 업로드
// ============================================================

async function uploadToR2(
  filename,
  buffer,
  contentType
) {
  await r2.send(
    new PutObjectCommand({
      Bucket: R2_BUCKET,

      Key: filename,

      Body: buffer,

      ContentType: contentType,
    })
  );
}


// ============================================================
// R2 삭제
// ============================================================

async function deleteFromR2(filename) {
  if (!filename) return;

  await r2.send(
    new DeleteObjectCommand({
      Bucket: R2_BUCKET,
      Key: filename,
    })
  );
}


// ============================================================
// 사진 목록
// ============================================================

async function listPhotos(
  month,
  voterId,
  admin,
  ownerId
) {
  const result = await db.query(
    `
    SELECT
      p.id,
      p.nickname,
      p.caption,
      p.filename,
      p.thumb,
      p.owner_id,

      (
        SELECT COUNT(*)
        FROM votes v
        WHERE v.photo_id = p.id
      ) AS votes,

      EXISTS(
        SELECT 1
        FROM votes v
        WHERE
          v.photo_id = p.id
          AND v.voter_id = $1
      ) AS voted

    FROM photos p

    WHERE p.month = $2

    ORDER BY p.id DESC
    `,
    [
      voterId || '',
      month,
    ]
  );

  return result.rows.map((row) => {
    const photo = {
      id: Number(row.id),

      nickname: row.nickname,

      caption: row.caption,

      url: urlOf(row.filename),

      thumb: row.thumb
        ? urlOf(row.thumb)
        : urlOf(row.filename),

      voted: Boolean(row.voted),

      own:
        Boolean(ownerId) &&
        row.owner_id === ownerId,
    };

    if (admin) {
      photo.votes =
        Number(row.votes);
    }

    return photo;
  });
}


// ============================================================
// 사진 삭제
// ============================================================

async function removePhoto(id) {
  const result = await db.query(
    `
    SELECT
      filename,
      thumb
    FROM photos
    WHERE id = $1
    `,
    [id]
  );

  const row = result.rows[0];

  if (!row) {
    return;
  }

  await db.query(
    `
    DELETE FROM photos
    WHERE id = $1
    `,
    [id]
  );

  // DB 삭제 후 R2 삭제
  for (
    const filename of [
      row.filename,
      row.thumb,
    ]
  ) {
    if (!filename) continue;

    try {
      await deleteFromR2(filename);
    } catch (error) {
      console.error(
        'R2 파일 삭제 실패:',
        filename,
        error
      );
    }
  }
}


// ============================================================
// API
// ============================================================

async function api(req, res, url) {
  const pathname = url.pathname;
  const method = req.method;


  // ----------------------------------------------------------
  // 서버 설정
  // ----------------------------------------------------------

  if (
    pathname === '/api/config' &&
    method === 'GET'
  ) {
    return send(res, 200, {
      maxPerUser: MAX_PER_USER,
      maxImageMB: MAX_IMAGE_MB,
    });
  }


  // ----------------------------------------------------------
  // 관리자 확인
  // ----------------------------------------------------------

  if (
    pathname === '/api/admin/check' &&
    method === 'GET'
  ) {
    const admin = isAdmin(req);

    return send(
      res,
      admin ? 200 : 401,
      { admin }
    );
  }


  // ----------------------------------------------------------
  // 현재 로그인 사용자
  // ----------------------------------------------------------

  if (
    pathname === '/api/me' &&
    method === 'GET'
  ) {
    const user =
      await authenticatedUser(req);

    return send(res, 200, {
      user: user
        ? {
            id: user.id,
            nickname: user.nickname,
          }
        : null,
    });
  }


  // ----------------------------------------------------------
  // 회원가입
  // ----------------------------------------------------------

  if (
    pathname === '/api/register' &&
    method === 'POST'
  ) {
    const body =
      await readJson(req);

    const nickname =
      cleanNick(body.nickname);

    const nickKey =
      nickKeyOf(nickname);

    const pin =
      String(body.pin || '');


    if (!nickname) {
      return send(res, 400, {
        error:
          '닉네임을 입력해주세요.',
      });
    }


    if (!/^\d{4}$/.test(pin)) {
      return send(res, 400, {
        error:
          '비밀번호는 숫자 4자리로 입력해주세요.',
      });
    }


    const id =
      crypto.randomUUID();

    const salt =
      crypto.randomBytes(16)
        .toString('hex');

    const hash =
      pinHash(
        pin,
        salt
      ).toString('hex');


    try {
      await db.query(
        `
        INSERT INTO users
          (
            id,
            nickname,
            nick_key,
            pin_salt,
            pin_hash
          )
        VALUES
          ($1, $2, $3, $4, $5)
        `,
        [
          id,
          nickname,
          nickKey,
          salt,
          hash,
        ]
      );
    } catch (error) {
      if (
        error.code === '23505'
      ) {
        return send(res, 409, {
          error:
            '이미 사용 중인 닉네임입니다.',
        });
      }

      throw error;
    }


    setSession(
      res,
      id
    );


    return send(res, 201, {
      user: {
        id,
        nickname,
      },
    });
  }


  // ----------------------------------------------------------
  // 로그인
  // ----------------------------------------------------------

  if (
    pathname === '/api/login' &&
    method === 'POST'
  ) {
    const body =
      await readJson(req);

    const nickname =
      cleanNick(body.nickname);

    const nickKey =
      nickKeyOf(nickname);

    const pin =
      String(body.pin || '');

    const bucket =
      attemptBucket(
        req,
        nickKey
      );


    if (
      await isLoginBlocked(bucket)
    ) {
      return send(res, 429, {
        error:
          '로그인 시도가 제한되었습니다. 잠시 후 다시 시도해주세요.',
      });
    }


    const result =
      await db.query(
        `
        SELECT
          id,
          nickname,
          pin_salt,
          pin_hash

        FROM users

        WHERE nick_key = $1
        `,
        [nickKey]
      );


    const user =
      result.rows[0];


    /*
      존재하지 않는 닉네임에서도
      어느 정도 동일한 계산을 수행해
      계정 존재 여부를 바로 추측하기 어렵게 합니다.
    */

    const salt =
      user?.pin_salt ||
      'unknown-user-salt';


    const expected =
      user
        ? Buffer.from(
            user.pin_hash,
            'hex'
          )
        : pinHash(
            '0000',
            salt
          );


    const candidate =
      pinHash(
        /^\d{4}$/.test(pin)
          ? pin
          : '0000',
        salt
      );


    const valid =
      Boolean(user) &&
      expected.length ===
        candidate.length &&
      crypto.timingSafeEqual(
        expected,
        candidate
      );


    if (!valid) {
      await failLogin(
        bucket
      );

      return send(res, 401, {
        error:
          '닉네임 또는 비밀번호가 올바르지 않습니다.',
      });
    }


    await db.query(
      `
      DELETE FROM login_attempts
      WHERE bucket = $1
      `,
      [bucket]
    );


    setSession(
      res,
      user.id
    );


    return send(res, 200, {
      user: {
        id: user.id,
        nickname: user.nickname,
      },
    });
  }


  // ----------------------------------------------------------
  // 로그아웃
  // ----------------------------------------------------------

  if (
    pathname === '/api/logout' &&
    method === 'POST'
  ) {
    clearSession(res);

    return send(res, 200, {
      ok: true,
    });
  }


  // ----------------------------------------------------------
  // 사진 목록
  // ----------------------------------------------------------

  if (
    pathname === '/api/photos' &&
    method === 'GET'
  ) {
    const month =
      url.searchParams.get(
        'month'
      );


    if (!validMonth(month)) {
      return send(res, 400, {
        error:
          '올바른 월이 아닙니다.',
      });
    }


    const admin =
      isAdmin(req);

    const user =
      await authenticatedUser(req);

    const voterId =
      user?.id || '';

    const ownerId =
      user?.id || '';


    const photos =
      await listPhotos(
        month,
        voterId,
        admin,
        ownerId
      );


    let mine = 0;


    if (user) {
      const result =
        await db.query(
          `
          SELECT COUNT(*) AS c
          FROM photos
          WHERE owner_id = $1
          `,
          [user.id]
        );

      mine =
        Number(result.rows[0].c);
    }


    return send(res, 200, {
      photos,

      mine,

      admin,

      user:
        user
          ? {
              id: user.id,
              nickname: user.nickname,
            }
          : null,
    });
  }


  // ----------------------------------------------------------
  // 사진 원본 업로드
  // ----------------------------------------------------------

  if (
    pathname === '/api/photos' &&
    method === 'POST'
  ) {
    const user =
      await requireUser(
        req,
        res
      );


    if (!user) {
      req.resume();
      return;
    }


    const month =
      hdr(req, 'x-month');


    if (!validMonth(month)) {
      req.resume();

      return send(res, 400, {
        error:
          '올바른 월이 아닙니다.',
      });
    }


    const contentLength =
      Number(
        req.headers[
          'content-length'
        ] || 0
      );


    if (
      contentLength > MAX_BYTES
    ) {
      req.resume();

      return send(res, 413, {
        error:
          `사진은 장당 ${MAX_IMAGE_MB}MB까지 올릴 수 있어요.`,
      });
    }


    const countResult =
      await db.query(
        `
        SELECT COUNT(*) AS c
        FROM photos
        WHERE owner_id = $1
        `,
        [user.id]
      );


    const count =
      Number(
        countResult.rows[0].c
      );


    if (
      count >= MAX_PER_USER
    ) {
      req.resume();

      return send(res, 409, {
        error:
          `한 사람당 전체 ${MAX_PER_USER}장까지만 올릴 수 있어요.`,
      });
    }


    const buffer =
      await readBody(
        req,
        MAX_BYTES
      );


    const extension =
      sniff(buffer);


    if (!extension) {
      return send(res, 400, {
        error:
          'JPG, PNG, WEBP 이미지만 올릴 수 있어요.',
      });
    }


    const filename =
      crypto.randomUUID() +
      '.' +
      extension;


    const contentType =
      contentTypeFor(
        extension
      );


    // 먼저 R2에 업로드
    await uploadToR2(
      filename,
      buffer,
      contentType
    );


    try {
      const result =
        await db.query(
          `
          INSERT INTO photos
            (
              month,
              nickname,
              nick_key,
              caption,
              filename,
              owner_id
            )
          VALUES
            ($1, $2, $3, $4, $5, $6)

          RETURNING id
          `,
          [
            month,
            user.nickname,
            user.nick_key,
            '',
            filename,
            user.id,
          ]
        );


      return send(res, 201, {
        id:
          Number(
            result.rows[0].id
          ),

        mine:
          count + 1,
      });
    } catch (error) {

      // DB 저장 실패 시
      // 이미 올라간 R2 파일 삭제
      try {
        await deleteFromR2(
          filename
        );
      } catch (cleanupError) {
        console.error(
          'R2 정리 실패:',
          cleanupError
        );
      }

      throw error;
    }
  }


  let match;


  // ----------------------------------------------------------
  // 썸네일 업로드
  // ----------------------------------------------------------

  if (
    (
      match =
        /^\/api\/photos\/(\d+)\/thumb$/
          .exec(pathname)
    ) &&
    method === 'POST'
  ) {
    const user =
      await requireUser(
        req,
        res
      );


    if (!user) {
      req.resume();
      return;
    }


    const id =
      Number(match[1]);


    const result =
      await db.query(
        `
        SELECT
          owner_id,
          thumb

        FROM photos

        WHERE id = $1
        `,
        [id]
      );


    const row =
      result.rows[0];


    if (!row) {
      req.resume();

      return send(res, 404, {
        error:
          '사진을 찾을 수 없어요.',
      });
    }


    if (
      row.owner_id !== user.id ||
      row.thumb
    ) {
      req.resume();

      return send(res, 403, {
        error:
          '권한이 없어요.',
      });
    }


    const buffer =
      await readBody(
        req,
        2 * 1024 * 1024
      );


    if (
      sniff(buffer) !== 'jpg'
    ) {
      return send(res, 400, {
        error:
          '썸네일은 JPG만 가능해요.',
      });
    }


    const filename =
      't-' +
      crypto.randomUUID() +
      '.jpg';


    await uploadToR2(
      filename,
      buffer,
      'image/jpeg'
    );


    try {
      await db.query(
        `
        UPDATE photos

        SET thumb = $1

        WHERE
          id = $2
          AND owner_id = $3
        `,
        [
          filename,
          id,
          user.id,
        ]
      );
    } catch (error) {

      try {
        await deleteFromR2(
          filename
        );
      } catch (cleanupError) {
        console.error(
          'R2 썸네일 정리 실패:',
          cleanupError
        );
      }

      throw error;
    }


    return send(res, 200, {
      ok: true,
    });
  }


  // ----------------------------------------------------------
  // 투표
  // ----------------------------------------------------------

  if (
    (
      match =
        /^\/api\/photos\/(\d+)\/vote$/
          .exec(pathname)
    ) &&
    method === 'POST'
  ) {
    const user =
      await requireUser(
        req,
        res
      );


    if (!user) {
      return;
    }


    const id =
      Number(match[1]);


    const photoResult =
      await db.query(
        `
        SELECT owner_id
        FROM photos
        WHERE id = $1
        `,
        [id]
      );


    const photo =
      photoResult.rows[0];


    if (!photo) {
      return send(res, 404, {
        error:
          '사진을 찾을 수 없어요.',
      });
    }


    if (
      photo.owner_id &&
      photo.owner_id === user.id
    ) {
      return send(res, 403, {
        error:
          '내 사진에는 투표할 수 없어요.',
      });
    }


    const voteResult =
      await db.query(
        `
        SELECT 1
        FROM votes

        WHERE
          photo_id = $1
          AND voter_id = $2
        `,
        [
          id,
          user.id,
        ]
      );


    const had =
      voteResult.rowCount > 0;


    if (had) {
      await db.query(
        `
        DELETE FROM votes

        WHERE
          photo_id = $1
          AND voter_id = $2
        `,
        [
          id,
          user.id,
        ]
      );
    } else {
      await db.query(
        `
        INSERT INTO votes
          (
            photo_id,
            voter_id
          )
        VALUES
          ($1, $2)
        `,
        [
          id,
          user.id,
        ]
      );
    }


    return send(res, 200, {
      voted: !had,
    });
  }


  // ----------------------------------------------------------
  // 사진 삭제
  // ----------------------------------------------------------

  if (
    (
      match =
        /^\/api\/photos\/(\d+)$/
          .exec(pathname)
    ) &&
    method === 'DELETE'
  ) {
    const id =
      Number(match[1]);


    const admin =
      isAdmin(req);


    const user =
      await authenticatedUser(req);


    const result =
      await db.query(
        `
        SELECT owner_id
        FROM photos
        WHERE id = $1
        `,
        [id]
      );


    const row =
      result.rows[0];


    if (!row) {
      return send(res, 200, {
        ok: true,
      });
    }


    const isOwner =
      Boolean(user) &&
      row.owner_id === user.id;


    if (
      !admin &&
      !isOwner
    ) {
      return send(res, 403, {
        error:
          '본인이 올린 사진만 삭제할 수 있어요.',
      });
    }


    await removePhoto(id);


    return send(res, 200, {
      ok: true,
    });
  }


  // ----------------------------------------------------------
  // 관리자 랭킹
  // ----------------------------------------------------------

  if (
    pathname === '/api/admin/ranking' &&
    method === 'GET'
  ) {
    if (!isAdmin(req)) {
      return send(res, 401, {
        error:
          '관리자 키가 필요해요.',
      });
    }


    const result =
      await db.query(
        `
        SELECT
          p.id,
          p.month,
          p.nickname,
          p.caption,
          p.filename,
          p.thumb,

          (
            SELECT COUNT(*)
            FROM votes v
            WHERE v.photo_id = p.id
          ) AS votes

        FROM photos p

        ORDER BY
          p.month DESC,
          votes DESC,
          p.id
        `
      );


    const rows =
      result.rows;


    const byMonth =
      new Map();


    for (const row of rows) {
      let group =
        byMonth.get(
          row.month
        );


      if (!group) {
        group = {
          month: row.month,

          total: 0,

          ranks: [],
        };

        byMonth.set(
          row.month,
          group
        );
      }


      group.total++;


      const votes =
        Number(row.votes);


      if (votes > 0) {

        let rank =
          group.ranks.find(
            (item) =>
              item.votes === votes
          );


        if (
          !rank &&
          group.ranks.length < 3
        ) {
          rank = {
            rank:
              group.ranks.length + 1,

            votes,

            photos: [],
          };


          group.ranks.push(
            rank
          );
        }


        if (rank) {
          rank.photos.push({
            id:
              Number(row.id),

            nickname:
              row.nickname,

            caption:
              row.caption,

            url:
              urlOf(
                row.filename
              ),

            thumb:
              row.thumb
                ? urlOf(
                    row.thumb
                  )
                : urlOf(
                    row.filename
                  ),

            votes,
          });
        }
      }
    }


    return send(res, 200, {
      months:
        [...byMonth.values()],
    });
  }


  // ----------------------------------------------------------
  // 없는 API
  // ----------------------------------------------------------

  return send(res, 404, {
    error: 'not found',
  });
}


// ============================================================
// 정적 파일
// ============================================================

function serveStatic(
  res,
  base,
  relativePath
) {
  const root =
    path.resolve(base);


  const file =
    path.resolve(
      root,
      relativePath
    );


  // Path Traversal 방지
  if (
    file !== root &&
    !file.startsWith(
      root + path.sep
    )
  ) {
    res.writeHead(403);

    return res.end();
  }


  fs.readFile(
    file,
    (error, data) => {
      if (error) {
        res.writeHead(404);

        return res.end(
          'Not found'
        );
      }


      const extension =
        path.extname(
          file
        ).toLowerCase();


      res.writeHead(
        200,
        {
          'Content-Type':
            MIME[extension] ||
            'application/octet-stream',

          'Cache-Control':
            'no-cache',
        }
      );


      res.end(data);
    }
  );
}


// ============================================================
// HTTP 서버
// ============================================================

const server =
  http.createServer(
    async (req, res) => {
      const url =
        new URL(
          req.url,
          'http://localhost'
        );


      try {

        // API
        if (
          url.pathname.startsWith(
            '/api/'
          )
        ) {
          return await api(
            req,
            res,
            url
          );
        }


        // 관리자 페이지
        if (
          url.pathname ===
          '/admin'
        ) {
          url.pathname =
            '/admin.html';
        }


        // 일반 정적 파일
        return serveStatic(
          res,
          PUBLIC_DIR,
          url.pathname === '/'
            ? 'index.html'
            : url.pathname.slice(1)
        );

      } catch (error) {

        console.error(
          '서버 오류:',
          error
        );


        const code =
          error.message ===
          'too_large'
            ? 413
            : error.message ===
              'bad_json'
              ? 400
              : 500;


        if (
          !res.headersSent
        ) {
          send(
            res,
            code,
            {
              error:
                code === 413
                  ? `파일이 너무 커요. (최대 ${MAX_IMAGE_MB}MB)`
                  : code === 400
                    ? '요청이 올바르지 않아요.'
                    : '서버 오류가 발생했어요.',
            }
          );
        }
      }
    }
  );


// ============================================================
// 서버 시작
// ============================================================

async function startServer() {
  try {

    // PostgreSQL 연결 테스트
    await db.query(
      'SELECT 1'
    );

    console.log(
      'PostgreSQL 연결 성공'
    );


    // 테이블 생성
    await initializeDatabase();


    // 서버 실행
    server.listen(
      PORT,
      () => {
        console.log(
          `필카톡 서버 실행 중: PORT ${PORT}`
        );

        console.log(
          `관리자 페이지: /admin`
        );

        console.log(
          `R2 Bucket: ${R2_BUCKET}`
        );
      }
    );

  } catch (error) {

    console.error(
      '서버 시작 실패:',
      error
    );

    process.exit(1);
  }
}


startServer();


// ============================================================
// 프로세스 종료 처리
// ============================================================

async function shutdown() {
  console.log(
    '서버 종료 중...'
  );

  server.close(
    async () => {
      await db.end();

      process.exit(0);
    }
  );
}


process.on(
  'SIGTERM',
  shutdown
);

process.on(
  'SIGINT',
  shutdown
);
