
/*
 * 필카톡 사진 동호회 서버
 * Node.js 22+
 * PostgreSQL + Cloudflare R2 + Render
 */
require('dotenv').config();
const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const { Pool } = require('pg');

const {
  S3Client,
  PutObjectCommand,
  GetObjectCommand,
  DeleteObjectCommand,
} = require('@aws-sdk/client-s3');

// ============================================================
// 기본 설정
// ============================================================

const PORT = Number(process.env.PORT || 3000);
const MAX_PER_USER = Number(process.env.MAX_PER_USER || 20);
const MAX_IMAGE_MB = Number(process.env.MAX_IMAGE_MB || 15);
const MAX_BYTES = MAX_IMAGE_MB * 1024 * 1024;

const SESSION_MS = 7 * 24 * 60 * 60 * 1000;

const LOGIN_MAX_ATTEMPTS = 5;
const LOGIN_WINDOW_MS = 15 * 60 * 1000;
const LOGIN_BLOCK_MS = 15 * 60 * 1000;

const PUBLIC_DIR = path.join(__dirname, 'public');

const DATABASE_URL = process.env.DATABASE_URL || '';
const SESSION_SECRET = process.env.SESSION_SECRET || '';
const ADMIN_KEY = process.env.ADMIN_KEY || '';

const R2_ENDPOINT = process.env.R2_ENDPOINT || '';
const R2_ACCESS_KEY_ID = process.env.R2_ACCESS_KEY_ID || '';
const R2_SECRET_ACCESS_KEY = process.env.R2_SECRET_ACCESS_KEY || '';
const R2_BUCKET = process.env.R2_BUCKET || '';
const R2_PUBLIC_URL = process.env.R2_PUBLIC_URL || '';

if (!DATABASE_URL) {
  throw new Error('DATABASE_URL 환경변수가 필요합니다.');
}

if (Buffer.byteLength(SESSION_SECRET) < 32) {
  throw new Error(
    'SESSION_SECRET은 32바이트 이상의 비밀값이어야 합니다.'
  );
}

if (!ADMIN_KEY) {
  throw new Error('ADMIN_KEY 환경변수를 설정하세요.');
}

const missingR2 = [];

if (!R2_ENDPOINT) missingR2.push('R2_ENDPOINT');
if (!R2_ACCESS_KEY_ID) missingR2.push('R2_ACCESS_KEY_ID');
if (!R2_SECRET_ACCESS_KEY) missingR2.push('R2_SECRET_ACCESS_KEY');
if (!R2_BUCKET) missingR2.push('R2_BUCKET');
if (!R2_PUBLIC_URL) missingR2.push('R2_PUBLIC_URL');

if (missingR2.length) {
  throw new Error(
    `R2 환경변수가 없습니다: ${missingR2.join(', ')}`
  );
}

const db = new Pool({
  connectionString: DATABASE_URL,
  ssl: { rejectUnauthorized: false },
});

const r2 = new S3Client({
  region: 'auto',
  endpoint: R2_ENDPOINT,
  credentials: {
    accessKeyId: R2_ACCESS_KEY_ID,
    secretAccessKey: R2_SECRET_ACCESS_KEY,
  },
});

// ============================================================
// 계절 / 입력값 처리
// ============================================================

const VALID_SEASONS = new Set([
  'spring',
  'summer',
  'autumn',
  'winter',
]);

function validSeason(season) {
  return VALID_SEASONS.has(season || '');
}

function validMonth(month) {
  return /^\d{4}-(0[1-9]|1[0-2])$/.test(month || '');
}

function seasonFromMonth(month) {
  if (!validMonth(month)) return null;

  const number = Number(month.slice(5, 7));

  if (number >= 3 && number <= 5) return 'spring';
  if (number >= 6 && number <= 8) return 'summer';
  if (number >= 9 && number <= 11) return 'autumn';

  return 'winter';
}

function cleanNick(value) {
  return String(value || '')
    .normalize('NFKC')
    .trim()
    .replace(/\s+/g, ' ')
    .slice(0, 20);
}

function nickKeyOf(nickname) {
  return cleanNick(nickname).toLocaleLowerCase('ko-KR');
}

function hdr(req, name) {
  try {
    return decodeURIComponent(String(req.headers[name] || ''));
  } catch {
    return '';
  }
}

// ============================================================
// 데이터베이스 초기화 및 기존 데이터 마이그레이션
// ============================================================

async function initializeDatabase() {
  await db.query(`
    CREATE TABLE IF NOT EXISTS users (
      id TEXT PRIMARY KEY,
      nickname TEXT NOT NULL,
      nick_key TEXT NOT NULL UNIQUE,
      pin_salt TEXT NOT NULL,
      pin_hash TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS photos (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      month TEXT,
      season TEXT,
      nickname TEXT NOT NULL,
      nick_key TEXT NOT NULL,
      caption TEXT DEFAULT '',
      filename TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      owner_id TEXT DEFAULT '',
      thumb TEXT DEFAULT ''
    )
  `);

  // 기존 데이터베이스에 season 컬럼 추가
  await db.query(`
    ALTER TABLE photos
    ADD COLUMN IF NOT EXISTS season TEXT
  `);

  // month의 월 문자열을 기준으로 기존 사진을 계절로 변환.
  // 문자열 비교를 사용하여 잘못된 month 값의 정수 변환 오류를 방지.
  // 이미 season 값이 있는 사진은 덮어쓰지 않는다.
  await db.query(`
    UPDATE photos
    SET season = CASE SUBSTRING(month FROM 6 FOR 2)
      WHEN '03' THEN 'spring'
      WHEN '04' THEN 'spring'
      WHEN '05' THEN 'spring'
      WHEN '06' THEN 'summer'
      WHEN '07' THEN 'summer'
      WHEN '08' THEN 'summer'
      WHEN '09' THEN 'autumn'
      WHEN '10' THEN 'autumn'
      WHEN '11' THEN 'autumn'
      WHEN '12' THEN 'winter'
      WHEN '01' THEN 'winter'
      WHEN '02' THEN 'winter'
      ELSE NULL
    END
    WHERE season IS NULL
      AND month ~ '^\\d{4}-(0[1-9]|1[0-2])$'
  `);

  // 새 업로드는 month 없이 저장한다.
  // 기존 사진의 month 값은 삭제하지 않는다.
  await db.query(`
    ALTER TABLE photos
    ALTER COLUMN month DROP NOT NULL
  `);

  await db.query(`
    CREATE INDEX IF NOT EXISTS idx_photos_month
    ON photos(month)
  `);

  await db.query(`
    CREATE INDEX IF NOT EXISTS idx_photos_season
    ON photos(season)
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS votes (
      photo_id INTEGER NOT NULL
        REFERENCES photos(id)
        ON DELETE CASCADE,
      voter_id TEXT NOT NULL,
      created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (photo_id, voter_id)
    )
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS admin_bookmarks (
      photo_id INTEGER PRIMARY KEY REFERENCES photos(id) ON DELETE CASCADE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);

  await db.query(`
    CREATE TABLE IF NOT EXISTS login_attempts (
      bucket TEXT PRIMARY KEY,
      count INTEGER NOT NULL DEFAULT 0,
      window_started BIGINT NOT NULL,
      blocked_until BIGINT NOT NULL DEFAULT 0
    )
  `);

  console.log('PostgreSQL 데이터베이스 초기화 완료');
}

// ============================================================
// 응답 및 관리자 인증
// ============================================================

function send(res, code, obj) {
  if (res.headersSent) return;

  res.writeHead(code, {
    'Content-Type': 'application/json; charset=utf-8',
    'Cache-Control': 'no-store',
  });

  res.end(JSON.stringify(obj));
}

function isAdmin(req) {
  const supplied = Buffer.from(
    String(req.headers['x-admin-key'] || '')
  );

  const expected = Buffer.from(ADMIN_KEY);

  return (
    supplied.length === expected.length &&
    crypto.timingSafeEqual(supplied, expected)
  );
}

// ============================================================
// 요청 본문 처리
// ============================================================

function readBody(req, limit) {
  return new Promise((resolve, reject) => {
    let size = 0;
    const chunks = [];
    let rejected = false;

    req.on('data', (chunk) => {
      if (rejected) return;

      size += chunk.length;

      if (size > limit) {
        rejected = true;
        reject(new Error('too_large'));
        req.resume();
        return;
      }

      chunks.push(chunk);
    });

    req.on('end', () => {
      if (!rejected) resolve(Buffer.concat(chunks));
    });

    req.on('error', (error) => {
      if (!rejected) {
        rejected = true;
        reject(error);
      }
    });
  });
}

async function readJson(req) {
  const buffer = await readBody(req, 64 * 1024);

  try {
    return JSON.parse(buffer.toString() || '{}');
  } catch {
    throw new Error('bad_json');
  }
}

// ============================================================
// 쿠키 및 세션
// ============================================================

function getCookie(req, name) {
  const cookies = String(req.headers.cookie || '').split(';');

  for (const part of cookies) {
    const i = part.indexOf('=');
    if (i < 0) continue;

    const key = part.slice(0, i).trim();
    if (key !== name) continue;

    try {
      return decodeURIComponent(part.slice(i + 1).trim());
    } catch {
      return '';
    }
  }

  return '';
}

function sign(payload) {
  return crypto
    .createHmac('sha256', SESSION_SECRET)
    .update(payload)
    .digest();
}

function setSession(res, userId) {
  const payload = Buffer.from(
    JSON.stringify({
      sub: userId,
      exp: Date.now() + SESSION_MS,
    })
  ).toString('base64url');

  const signature = sign(payload).toString('base64url');

  const secure =
    process.env.NODE_ENV === 'production' ? '; Secure' : '';

  res.setHeader(
    'Set-Cookie',
    `session=${payload}.${signature}; ` +
    `Path=/; HttpOnly; SameSite=Strict; ` +
    `Max-Age=${Math.floor(SESSION_MS / 1000)}` +
    secure
  );
}

function clearSession(res) {
  const secure =
    process.env.NODE_ENV === 'production' ? '; Secure' : '';

  res.setHeader(
    'Set-Cookie',
    `session=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0` +
    secure
  );
}

async function authenticatedUser(req) {
  const token = getCookie(req, 'session');
  const separator = token.lastIndexOf('.');

  if (separator < 1) return null;

  const payload = token.slice(0, separator);
  const signatureText = token.slice(separator + 1);

  const suppliedSignature = Buffer.from(
    signatureText,
    'base64url'
  );

  const expectedSignature = sign(payload);

  if (
    suppliedSignature.length !== expectedSignature.length ||
    !crypto.timingSafeEqual(suppliedSignature, expectedSignature)
  ) {
    return null;
  }

  try {
    const data = JSON.parse(
      Buffer.from(payload, 'base64url').toString()
    );

    if (
      !data.sub ||
      !Number.isFinite(data.exp) ||
      data.exp < Date.now()
    ) {
      return null;
    }

    const result = await db.query(
      `
      SELECT id, nickname, nick_key
      FROM users
      WHERE id = $1
      `,
      [data.sub]
    );

    return result.rows[0] || null;
  } catch {
    return null;
  }
}

async function requireUser(req, res) {
  const user = await authenticatedUser(req);

  if (!user) {
    send(res, 401, {
      error: '먼저 로그인해주세요.',
    });

    return null;
  }

  return user;
}

// ============================================================
// PIN 및 로그인 시도 제한
// ============================================================

function pinHash(pin, salt) {
  return crypto.scryptSync(pin, salt, 64);
}

function attemptBucket(req, nickKey) {
  const ip = req.socket.remoteAddress || 'unknown';

  return crypto
    .createHmac('sha256', SESSION_SECRET)
    .update(`${nickKey}\n${ip}`)
    .digest('hex');
}

async function isLoginBlocked(bucket) {
  const result = await db.query(
    `SELECT blocked_until FROM login_attempts WHERE bucket = $1`,
    [bucket]
  );

  const row = result.rows[0];

  return Boolean(row && Number(row.blocked_until) > Date.now());
}

async function failLogin(bucket) {
  const now = Date.now();

  const result = await db.query(
    `
    SELECT count, window_started
    FROM login_attempts
    WHERE bucket = $1
    `,
    [bucket]
  );

  const row = result.rows[0];

  const inWindow =
    row && now - Number(row.window_started) < LOGIN_WINDOW_MS;

  const count = inWindow ? Number(row.count) + 1 : 1;
  const windowStarted = inWindow ? Number(row.window_started) : now;

  const blockedUntil =
    count >= LOGIN_MAX_ATTEMPTS ? now + LOGIN_BLOCK_MS : 0;

  await db.query(
    `
    INSERT INTO login_attempts
      (bucket, count, window_started, blocked_until)
    VALUES ($1, $2, $3, $4)
    ON CONFLICT(bucket)
    DO UPDATE SET
      count = EXCLUDED.count,
      window_started = EXCLUDED.window_started,
      blocked_until = EXCLUDED.blocked_until
    `,
    [bucket, count, windowStarted, blockedUntil]
  );
}

// ============================================================
// 이미지 형식 검사 및 R2
// ============================================================

function sniff(buffer) {
  if (
    buffer.length > 3 &&
    buffer[0] === 0xff &&
    buffer[1] === 0xd8 &&
    buffer[2] === 0xff
  ) {
    return 'jpg';
  }

  if (
    buffer.length >= 8 &&
    buffer.subarray(0, 8).equals(
      Buffer.from([
        0x89, 0x50, 0x4e, 0x47,
        0x0d, 0x0a, 0x1a, 0x0a,
      ])
    )
  ) {
    return 'png';
  }

  if (
    buffer.length >= 12 &&
    buffer.subarray(0, 4).toString() === 'RIFF' &&
    buffer.subarray(8, 12).toString() === 'WEBP'
  ) {
    return 'webp';
  }

  return null;
}

function contentTypeFor(extension) {
  switch (extension) {
    case 'jpg': return 'image/jpeg';
    case 'png': return 'image/png';
    case 'webp': return 'image/webp';
    default: return 'application/octet-stream';
  }
}

function urlOf(filename) {
  return (
    R2_PUBLIC_URL.replace(/\/$/, '') +
    '/' +
    encodeURIComponent(filename)
  );
}

function adminPhoto(row) {
  return {
    id: Number(row.id),
    month: row.photo_month || row.month || '',
    nickname: row.nickname,
    caption: row.caption || '',
    url: urlOf(row.filename),
    thumb: row.thumb ? urlOf(row.thumb) : urlOf(row.filename),
    votes: Number(row.votes || 0),
    bookmarked: Boolean(row.bookmarked),
    createdAt: row.created_at,
  };
}

async function uploadToR2(filename, buffer, contentType) {
  await r2.send(
    new PutObjectCommand({
      Bucket: R2_BUCKET,
      Key: filename,
      Body: buffer,
      ContentType: contentType,
    })
  );
}

async function deleteFromR2(filename) {
  if (!filename) return;

  await r2.send(
    new DeleteObjectCommand({
      Bucket: R2_BUCKET,
      Key: filename,
    })
  );
}

// ============================================================
// 사진 목록 조회
// ============================================================

async function listPhotos(season, voterId, admin, ownerId) {
  const result = await db.query(
    `
    SELECT
      p.id,
      p.nickname,
      p.caption,
      p.filename,
      p.thumb,
      p.owner_id,

      (
        SELECT COUNT(*)
        FROM votes v
        WHERE v.photo_id = p.id
      ) AS votes,

      EXISTS(
        SELECT 1
        FROM votes v
        WHERE v.photo_id = p.id
          AND v.voter_id = $1
      ) AS voted

    FROM photos p
    WHERE p.season = $2
    ORDER BY p.id DESC
    `,
    [voterId || '', season]
  );

  return result.rows.map((row) => {
    const photo = {
      id: Number(row.id),
      nickname: row.nickname,
      caption: row.caption,
      url: urlOf(row.filename),
      thumb: row.thumb ? urlOf(row.thumb) : urlOf(row.filename),
      voted: Boolean(row.voted),
      own: Boolean(ownerId) && row.owner_id === ownerId,
    };

    if (admin) {
      photo.votes = Number(row.votes);
    }

    return photo;
  });
}

// ============================================================
// 사진 삭제
// ============================================================

async function removePhoto(id) {
  const result = await db.query(
    `SELECT filename, thumb FROM photos WHERE id = $1`,
    [id]
  );

  const row = result.rows[0];
  if (!row) return;

  // votes는 FK의 ON DELETE CASCADE에 의해 함께 삭제된다.
  await db.query(`DELETE FROM photos WHERE id = $1`, [id]);

  for (const filename of [row.filename, row.thumb]) {
    if (!filename) continue;

    try {
      await deleteFromR2(filename);
    } catch (error) {
      console.error('R2 파일 삭제 실패:', filename, error);
    }
  }
}

// ============================================================
// API
// ============================================================

async function api(req, res, url) {
  const pathname = url.pathname;
  const method = req.method;
  let match;

  // 서버 설정
  if (pathname === '/api/config' && method === 'GET') {
    return send(res, 200, {
      maxPerUser: MAX_PER_USER,
      maxImageMB: MAX_IMAGE_MB,
    });
  }

  // 관리자 확인
  if (pathname === '/api/admin/check' && method === 'GET') {
    const admin = isAdmin(req);
    return send(res, admin ? 200 : 401, { admin });
  }

  // 현재 로그인 사용자
  if (pathname === '/api/me' && method === 'GET') {
    const user = await authenticatedUser(req);

    return send(res, 200, {
      user: user
        ? { id: user.id, nickname: user.nickname }
        : null,
    });
  }

  // 회원가입
  if (pathname === '/api/register' && method === 'POST') {
    const body = await readJson(req);
    const nickname = cleanNick(body.nickname);
    const nickKey = nickKeyOf(nickname);
    const pin = String(body.pin || '');

    if (!nickname) {
      return send(res, 400, {
        error: '닉네임을 입력해주세요.',
      });
    }

    if (!/^\d{4}$/.test(pin)) {
      return send(res, 400, {
        error: '비밀번호는 숫자 4자리로 입력해주세요.',
      });
    }

    const id = crypto.randomUUID();
    const salt = crypto.randomBytes(16).toString('hex');
    const hash = pinHash(pin, salt).toString('hex');

    try {
      await db.query(
        `
        INSERT INTO users
          (id, nickname, nick_key, pin_salt, pin_hash)
        VALUES ($1, $2, $3, $4, $5)
        `,
        [id, nickname, nickKey, salt, hash]
      );
    } catch (error) {
      if (error.code === '23505') {
        return send(res, 409, {
          error: '이미 사용 중인 닉네임입니다.',
        });
      }

      throw error;
    }

    setSession(res, id);

    return send(res, 201, {
      user: { id, nickname },
    });
  }

  // 로그인
  if (pathname === '/api/login' && method === 'POST') {
    const body = await readJson(req);
    const nickname = cleanNick(body.nickname);
    const nickKey = nickKeyOf(nickname);
    const pin = String(body.pin || '');
    const bucket = attemptBucket(req, nickKey);

    if (await isLoginBlocked(bucket)) {
      return send(res, 429, {
        error: '로그인 시도가 제한되었습니다. 잠시 후 다시 시도해주세요.',
      });
    }

    const result = await db.query(
      `
      SELECT id, nickname, pin_salt, pin_hash
      FROM users
      WHERE nick_key = $1
      `,
      [nickKey]
    );

    const user = result.rows[0];
    const salt = user?.pin_salt || 'unknown-user-salt';

    const expected = user
      ? Buffer.from(user.pin_hash, 'hex')
      : pinHash('0000', salt);

    const candidate = pinHash(
      /^\d{4}$/.test(pin) ? pin : '0000',
      salt
    );

    const valid =
      Boolean(user) &&
      expected.length === candidate.length &&
      crypto.timingSafeEqual(expected, candidate);

    if (!valid) {
      await failLogin(bucket);

      return send(res, 401, {
        error: '닉네임 또는 비밀번호가 올바르지 않습니다.',
      });
    }

    await db.query(
      `DELETE FROM login_attempts WHERE bucket = $1`,
      [bucket]
    );

    setSession(res, user.id);

    return send(res, 200, {
      user: { id: user.id, nickname: user.nickname },
    });
  }

  // 로그아웃
  if (pathname === '/api/logout' && method === 'POST') {
    clearSession(res);
    return send(res, 200, { ok: true });
  }

  // ----------------------------------------------------------
  // 사진 목록: ?season=spring|summer|autumn|winter
  // 이전 요청 ?month=YYYY-MM 도 임시 지원
  // ----------------------------------------------------------

  if (pathname === '/api/photos' && method === 'GET') {
    let season = url.searchParams.get('season');

    if (!season) {
      season = seasonFromMonth(url.searchParams.get('month'));
    }

    if (!validSeason(season)) {
      return send(res, 400, {
        error: '올바른 계절이 아닙니다.',
      });
    }

    const admin = isAdmin(req);
    const user = await authenticatedUser(req);

    const photos = await listPhotos(
      season,
      user?.id || '',
      admin,
      user?.id || ''
    );

    let mine = 0;

    if (user) {
      const result = await db.query(
        `SELECT COUNT(*) AS c FROM photos WHERE owner_id = $1`,
        [user.id]
      );

      mine = Number(result.rows[0].c);
    }

    return send(res, 200, {
      photos,
      mine,
      admin,
      season,
      user: user
        ? { id: user.id, nickname: user.nickname }
        : null,
    });
  }

  // ----------------------------------------------------------
  // 사진 업로드: x-season 헤더 사용
  // 이전 x-month 헤더도 임시 지원
  // ----------------------------------------------------------

  if (pathname === '/api/photos' && method === 'POST') {
    const user = await requireUser(req, res);

    if (!user) {
      req.resume();
      return;
    }

    const suppliedSeason = hdr(req, 'x-season');
    const legacyMonth = hdr(req, 'x-month');

    const season = suppliedSeason
      ? suppliedSeason
      : seasonFromMonth(legacyMonth);

    if (!validSeason(season)) {
      req.resume();

      return send(res, 400, {
        error: '올바른 계절이 아닙니다.',
      });
    }

    // 구형 프론트엔드의 월 정보만 기존 방식으로 보존
    const monthToSave =
      !suppliedSeason && validMonth(legacyMonth)
        ? legacyMonth
        : null;

    const contentLength = Number(req.headers['content-length'] || 0);

    if (contentLength > MAX_BYTES) {
      req.resume();

      return send(res, 413, {
        error: `사진은 장당 ${MAX_IMAGE_MB}MB까지 올릴 수 있어요.`,
      });
    }

    const countResult = await db.query(
      `SELECT COUNT(*) AS c FROM photos WHERE owner_id = $1`,
      [user.id]
    );

    const count = Number(countResult.rows[0].c);

    if (count >= MAX_PER_USER) {
      req.resume();

      return send(res, 409, {
        error: `한 사람당 전체 ${MAX_PER_USER}장까지만 올릴 수 있어요.`,
      });
    }

    const buffer = await readBody(req, MAX_BYTES);
    const extension = sniff(buffer);

    if (!extension) {
      return send(res, 400, {
        error: 'JPG, PNG, WEBP 이미지만 올릴 수 있어요.',
      });
    }

    const filename = `${crypto.randomUUID()}.${extension}`;
    const contentType = contentTypeFor(extension);

    await uploadToR2(filename, buffer, contentType);

    try {
      const result = await db.query(
        `
        INSERT INTO photos
          (
            month,
            season,
            nickname,
            nick_key,
            caption,
            filename,
            owner_id
          )
        VALUES ($1, $2, $3, $4, $5, $6, $7)
        RETURNING id
        `,
        [
          monthToSave,
          season,
          user.nickname,
          user.nick_key,
          '',
          filename,
          user.id,
        ]
      );

      return send(res, 201, {
        id: Number(result.rows[0].id),
        mine: count + 1,
      });
    } catch (error) {
      // DB 저장 실패 시 R2에 업로드한 파일 정리
      try {
        await deleteFromR2(filename);
      } catch (cleanupError) {
        console.error('R2 정리 실패:', cleanupError);
      }

      throw error;
    }
  }

  // 썸네일 업로드
  if (
    (match = /^\/api\/photos\/(\d+)\/thumb$/.exec(pathname)) &&
    method === 'POST'
  ) {
    const user = await requireUser(req, res);

    if (!user) {
      req.resume();
      return;
    }

    const id = Number(match[1]);

    const result = await db.query(
      `SELECT owner_id, thumb FROM photos WHERE id = $1`,
      [id]
    );

    const row = result.rows[0];

    if (!row) {
      req.resume();

      return send(res, 404, {
        error: '사진을 찾을 수 없어요.',
      });
    }

    if (row.owner_id !== user.id || row.thumb) {
      req.resume();

      return send(res, 403, {
        error: '권한이 없어요.',
      });
    }

    const buffer = await readBody(req, 2 * 1024 * 1024);

    if (sniff(buffer) !== 'jpg') {
      return send(res, 400, {
        error: '썸네일은 JPG만 가능해요.',
      });
    }

    const filename = `t-${crypto.randomUUID()}.jpg`;

    await uploadToR2(filename, buffer, 'image/jpeg');

    try {
      const update = await db.query(
        `
        UPDATE photos
        SET thumb = $1
        WHERE id = $2 AND owner_id = $3 AND thumb = ''
        `,
        [filename, id, user.id]
      );

      // 기존 thumb 값이 NULL인 행도 허용
      if (update.rowCount === 0) {
        const retry = await db.query(
          `
          UPDATE photos
          SET thumb = $1
          WHERE id = $2 AND owner_id = $3 AND thumb IS NULL
          `,
          [filename, id, user.id]
        );

        if (retry.rowCount === 0) {
          await deleteFromR2(filename);

          return send(res, 409, {
            error: '썸네일이 이미 등록되었거나 사진을 찾을 수 없어요.',
          });
        }
      }
    } catch (error) {
      try {
        await deleteFromR2(filename);
      } catch (cleanupError) {
        console.error('R2 썸네일 정리 실패:', cleanupError);
      }

      throw error;
    }

    return send(res, 200, { ok: true });
  }

  // 투표
  if (
    (match = /^\/api\/photos\/(\d+)\/vote$/.exec(pathname)) &&
    method === 'POST'
  ) {
    const user = await requireUser(req, res);

    if (!user) return;

    const id = Number(match[1]);

    const photoResult = await db.query(
      `SELECT owner_id FROM photos WHERE id = $1`,
      [id]
    );

    const photo = photoResult.rows[0];

    if (!photo) {
      return send(res, 404, {
        error: '사진을 찾을 수 없어요.',
      });
    }

    if (photo.owner_id && photo.owner_id === user.id) {
      return send(res, 403, {
        error: '내 사진에는 투표할 수 없어요.',
      });
    }

    const voteResult = await db.query(
      `
      SELECT 1
      FROM votes
      WHERE photo_id = $1 AND voter_id = $2
      `,
      [id, user.id]
    );

    const had = voteResult.rowCount > 0;

    if (had) {
      await db.query(
        `
        DELETE FROM votes
        WHERE photo_id = $1 AND voter_id = $2
        `,
        [id, user.id]
      );
    } else {
      await db.query(
        `
        INSERT INTO votes (photo_id, voter_id)
        VALUES ($1, $2)
        ON CONFLICT (photo_id, voter_id) DO NOTHING
        `,
        [id, user.id]
      );
    }

    return send(res, 200, {
      voted: !had,
    });
  }

  // 사진 삭제
  if (
    (match = /^\/api\/photos\/(\d+)$/.exec(pathname)) &&
    method === 'DELETE'
  ) {
    const id = Number(match[1]);
    const admin = isAdmin(req);
    const user = await authenticatedUser(req);

    const result = await db.query(
      `SELECT owner_id FROM photos WHERE id = $1`,
      [id]
    );

    const row = result.rows[0];

    if (!row) {
      return send(res, 200, { ok: true });
    }

    const isOwner = Boolean(user) && row.owner_id === user.id;

    if (!admin && !isOwner) {
      return send(res, 403, {
        error: '본인이 올린 사진만 삭제할 수 있어요.',
      });
    }

    await removePhoto(id);

    return send(res, 200, { ok: true });
  }

  // 관리자 사진 목록과 북마크는 모두 PostgreSQL에 보관합니다.
  if (pathname.startsWith('/api/admin/')) {
    if (!isAdmin(req)) {
      return send(res, 401, {
        error: '관리자 키가 필요해요.',
      });
    }

    if (pathname === '/api/admin/bookmarks' && method === 'GET') {
      const result = await db.query(
        `SELECT p.id, CASE WHEN p.month ~ '^\\d{4}-(0[1-9]|1[0-2])$' THEN p.month
                  ELSE TO_CHAR(p.created_at, 'YYYY-MM') END AS photo_month,
          p.nickname, p.caption, p.filename, p.thumb,
          p.created_at,
          TRUE AS bookmarked,
          (SELECT COUNT(*)::int FROM votes v WHERE v.photo_id = p.id) AS votes
         FROM photos p JOIN admin_bookmarks b ON b.photo_id = p.id
         ORDER BY b.created_at DESC, p.id DESC`
      );
      return send(res, 200, { photos: result.rows.map(adminPhoto) });
    }

    if (pathname === '/api/admin/bookmarks' && method === 'POST') {
      const body = await readJson(req);
      const id = Number(body.photoId);
      if (!Number.isSafeInteger(id) || id < 1) {
        return send(res, 400, { error: '사진 정보가 올바르지 않아요.' });
      }
      const saved = await db.query(
        `INSERT INTO admin_bookmarks(photo_id) SELECT id FROM photos WHERE id = $1
         ON CONFLICT(photo_id) DO NOTHING RETURNING photo_id`, [id]
      );
      if (!saved.rowCount && !(await db.query('SELECT 1 FROM photos WHERE id = $1', [id])).rowCount) {
        return send(res, 404, { error: '사진을 찾을 수 없어요.' });
      }
      return send(res, 200, { bookmarked: true });
    }

    if ((match = /^\/api\/admin\/bookmarks\/(\d+)$/.exec(pathname)) && method === 'DELETE') {
      await db.query('DELETE FROM admin_bookmarks WHERE photo_id = $1', [Number(match[1])]);
      return send(res, 200, { bookmarked: false });
    }

    if (pathname === '/api/admin/photos' && method === 'GET') {
      const month = url.searchParams.get('month');
      if (!validMonth(month)) return send(res, 400, { error: '올바른 월이 아닙니다.' });
      const result = await db.query(
        `SELECT p.id, CASE WHEN p.month ~ '^\\d{4}-(0[1-9]|1[0-2])$' THEN p.month
                  ELSE TO_CHAR(p.created_at, 'YYYY-MM') END AS photo_month,
          p.nickname, p.caption, p.filename, p.thumb, p.created_at,
          (SELECT COUNT(*)::int FROM votes v WHERE v.photo_id = p.id) AS votes,
          EXISTS(SELECT 1 FROM admin_bookmarks b WHERE b.photo_id = p.id) AS bookmarked
         FROM photos p
         WHERE CASE WHEN p.month ~ '^\\d{4}-(0[1-9]|1[0-2])$' THEN p.month
                    ELSE TO_CHAR(p.created_at, 'YYYY-MM') END = $1
         ORDER BY votes DESC, p.id DESC`, [month]
      );
      return send(res, 200, { photos: result.rows.map(adminPhoto) });
    }

    if ((match = /^\/api\/admin\/photos\/(\d+)\/download$/.exec(pathname)) && method === 'GET') {
      const photo = (await db.query('SELECT filename FROM photos WHERE id = $1', [Number(match[1])])).rows[0];
      if (!photo) return send(res, 404, { error: '사진을 찾을 수 없어요.' });
      const object = await r2.send(new GetObjectCommand({ Bucket: R2_BUCKET, Key: photo.filename }));
      const safeName = `filcatalk_${Number(match[1])}${path.extname(photo.filename).toLowerCase()}`;
      res.writeHead(200, {
        'Content-Type': contentTypeFor(path.extname(photo.filename).slice(1)),
        'Content-Disposition': `attachment; filename="${safeName}"`,
        'Cache-Control': 'private, no-store',
        'X-Content-Type-Options': 'nosniff',
      });
      object.Body.on('error', (error) => {
        console.error('R2 원본 다운로드 실패:', error);
        if (!res.headersSent) send(res, 502, { error: '원본을 내려받지 못했어요.' });
        else res.destroy(error);
      });
      object.Body.pipe(res);
      return;
    }

    if (pathname === '/api/admin/ranking' && method === 'GET') {
      const result = await db.query(
        `SELECT p.id,
          CASE WHEN p.month ~ '^\\d{4}-(0[1-9]|1[0-2])$' THEN p.month
               ELSE TO_CHAR(p.created_at, 'YYYY-MM') END AS photo_month,
          p.nickname, p.caption, p.filename, p.thumb, p.created_at,
          (SELECT COUNT(*)::int FROM votes v WHERE v.photo_id = p.id) AS votes,
          EXISTS(SELECT 1 FROM admin_bookmarks b WHERE b.photo_id = p.id) AS bookmarked
         FROM photos p
         ORDER BY photo_month DESC, votes DESC, p.id DESC`
      );
      const byMonth = new Map();
      for (const row of result.rows) {
        const month = row.photo_month;
        if (!byMonth.has(month)) byMonth.set(month, { month, total: 0, ranks: [], photos: [] });
        const group = byMonth.get(month);
        const photo = adminPhoto(row);
        group.total++;
        group.photos.push(photo);
        const votes = Number(row.votes);
        if (votes < 1) continue;
        let rank = group.ranks.find((item) => item.votes === votes);
        if (!rank && group.ranks.length < 3) {
          rank = { rank: group.ranks.length + 1, votes, photos: [] };
          group.ranks.push(rank);
        }
        if (rank) rank.photos.push(photo);
      }
      return send(res, 200, { months: [...byMonth.values()] });
    }
  }

  return send(res, 404, {
    error: 'not found',
  });
}

// ============================================================
// 정적 파일
// ============================================================

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.png': 'image/png',
  '.webp': 'image/webp',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon',
};

function serveStatic(res, base, relativePath) {
  const root = path.resolve(base);
  const file = path.resolve(root, relativePath);

  // Path Traversal 방지
  if (file !== root && !file.startsWith(root + path.sep)) {
    res.writeHead(403);
    return res.end();
  }

  fs.readFile(file, (error, data) => {
    if (error) {
      res.writeHead(404);
      return res.end('Not found');
    }

    const extension = path.extname(file).toLowerCase();

    res.writeHead(200, {
      'Content-Type':
        MIME[extension] || 'application/octet-stream',
      'Cache-Control': 'no-cache',
      'X-Content-Type-Options': 'nosniff',
    });

    res.end(data);
  });
}

// ============================================================
// HTTP 서버
// ============================================================

const server = http.createServer(async (req, res) => {
  const url = new URL(req.url, 'http://localhost');

  try {
    if (url.pathname.startsWith('/api/')) {
      return await api(req, res, url);
    }

    if (url.pathname === '/admin') {
      url.pathname = '/admin.html';
    }

    return serveStatic(
      res,
      PUBLIC_DIR,
      url.pathname === '/'
        ? 'index.html'
        : url.pathname.slice(1)
    );
  } catch (error) {
    console.error('서버 오류:', error);

    const code =
      error.message === 'too_large'
        ? 413
        : error.message === 'bad_json'
          ? 400
          : 500;

    if (!res.headersSent) {
      send(res, code, {
        error:
          code === 413
            ? `파일이 너무 커요. (최대 ${MAX_IMAGE_MB}MB)`
            : code === 400
              ? '요청이 올바르지 않아요.'
              : '서버 오류가 발생했어요.',
      });
    } else if (!res.writableEnded) {
      res.end();
    }
  }
});

// ============================================================
// 서버 시작 및 종료
// ============================================================

async function startServer() {
  try {
    await db.query('SELECT 1');
    console.log('PostgreSQL 연결 성공');

    await initializeDatabase();

    server.listen(PORT, () => {
      console.log(`필카톡 서버 실행 중: PORT ${PORT}`);
      console.log('관리자 페이지: /admin');
      console.log(`R2 Bucket: ${R2_BUCKET}`);
    });
  } catch (error) {
    console.error('서버 시작 실패:', error);
    await db.end().catch(() => {});
    process.exit(1);
  }
}

async function shutdown() {
  console.log('서버 종료 중...');

  server.close(async () => {
    await db.end();
    process.exit(0);
  });
}

process.on('SIGTERM', shutdown);
process.on('SIGINT', shutdown);

startServer();
